export const maxDuration=300;
import {z} from 'zod';
import {criterionSchema,analysisSchema,assertFairCriteria,professionalText} from '@/lib/validation';
import {owner,readData,aiConfigured,checkOrigin,apiError,HttpError} from '@/lib/server';
import {claude,obj,str,list} from '@/lib/claude';
import {draftCriteria,termAnalysis,type Analysis} from '@/lib/domain';
export async function POST(request:Request){try{checkOrigin(request);const id=await owner();const input=z.object({action:z.enum(['criteria','analyze']),description:z.string().optional(),jobId:z.string().optional(),criteria:z.unknown().optional()}).parse(await request.json());if(input.action==='criteria'){const description=z.string().min(10).max(20000).parse(input.description);if(!aiConfigured(id))return Response.json({criteria:draftCriteria(description),engine:'Busca por termos'});const schema=obj({criteria:list(obj({id:str,text:str,kind:{enum:['experiencia','condicao','entrevista'],type:'string'},priority:{enum:['obrigatorio','diferencial','confirmar'],type:'string'}}))});const result=await claude(schema,[{type:'text',text:'Divida este briefing em critérios atômicos, sem adicionar exigências. Classifique experiência, condição a confirmar e comportamento para entrevista. Dê IDs únicos. Use confirmar quando a importância não for explícita.\nBRIEFING: '+description}],id);const criteria=z.array(criterionSchema).min(1).max(30).parse(result.criteria);assertFairCriteria(criteria);return Response.json({criteria,engine:'Claude'})}
if(input.action!=='analyze')throw new HttpError('Ação desconhecida.');const criteria=z.array(criterionSchema).min(1).max(30).parse(input.criteria);assertFairCriteria(criteria);const data=await readData(id);const job=data.jobs.find(j=>j.id===input.jobId);if(!job)throw new HttpError('Vaga não encontrada.',404);const candidates=data.candidates.map(c=>({...c,text:professionalText(c.text)}));if(!aiConfigured(id))return Response.json({analyses:termAnalysis(candidates,criteria),engine:'Busca por termos'});
// Sequential bounded batches avoid sending the entire talent database in a single request.
if(candidates.length>100)throw new HttpError('Nesta primeira versão, compare até 100 perfis por vez. A busca em bases maiores precisa do processamento em lotes.');const analyses:Analysis[]=[];const schema=obj({analyses:list(obj({candidateId:str,evidence:list(obj({criterionId:str,status:{type:'string',enum:['encontrada','confirmar']},quote:str,explanation:str,question:str}))}))});for(let i=0;i<candidates.length;i+=5){const batch=candidates.slice(i,i+5);const result=await claude(schema,[{type:'text',text:'Compare TODOS os critérios para CADA candidato. Não classifique nem elimine pessoas. Use encontrada apenas quando há trecho literal específico que sustenta a experiência; caso contrário confirmar. Condições atuais e comportamento sempre confirmar. Em confirmar, quote deve ser vazio. Inclua uma pergunta objetiva para esclarecer cada critério.\n'+JSON.stringify({criteria,candidates:batch.map(c=>({id:c.id,text:c.text}))})}],id);const parsed=z.array(analysisSchema).parse(result.analyses);if(parsed.length!==batch.length||new Set(parsed.map(a=>a.candidateId)).size!==batch.length)throw new HttpError('A IA não analisou todos os perfis. Tente novamente.',502);for(const a of parsed){const c=batch.find(c=>c.id===a.candidateId);if(!c||a.evidence.length!==criteria.length||new Set(a.evidence.map(e=>e.criterionId)).size!==criteria.length)throw new HttpError('Resposta incompleta da IA.',502);for(const e of a.evidence){const k=criteria.find(k=>k.id===e.criterionId);if(!k)throw new HttpError('Critério desconhecido na resposta da IA.',502);if(k.kind!=='experiencia'||!e.quote.trim()||!c.text.includes(e.quote)){e.status='confirmar';e.quote='';e.explanation='Sem trecho literal validado. Confirme em conversa.'}if(e.status==='confirmar')e.quote=''}analyses.push(a)}}return Response.json({analyses,engine:'Claude'})}catch(e){if(e instanceof Error&&e.message.startsWith('Revise os critérios'))return Response.json({error:e.message},{status:400});return apiError(e)}}
