'use client';
import {useState,useMemo,useEffect} from 'react';
import {Star,MapPin,Clock3,FileText,ChevronRight,Users} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {Data,Job} from '@/lib/domain';
import {shortlistItems,filterShortlist} from '@/lib/candidate-shortlist';
import {contactStatusLabels} from '@/lib/contact-board';
import {appointmentActive,appointmentEnd} from '@/lib/interview-agenda';
import {brazilDate} from '@/lib/pt-br';
export default function CandidateShortlist({data,job,busy,onJob,onOpen,onRemove,onExplore}:{data:Data;job:Job;busy:boolean;onJob:(id:string)=>void;onOpen:(id:string,tab:string)=>void;onRemove:(id:string)=>void;onExplore:()=>void}){
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(1),[now,setNow]=useState(()=>Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer)},[]);
 const items=useMemo(()=>shortlistItems(data.candidates,job,data.records),[data.candidates,job,data.records]);
 const filtered=filterShortlist(items,query,status),pages=Math.max(1,Math.ceil(filtered.length/24)),current=Math.min(page,pages);
 return <><div className="shortlist-context"><div><label className="field-label" htmlFor="shortlist-job">Lista de interesse da vaga</label><select id="shortlist-job" className="text-input" value={job.id} onChange={e=>{onJob(e.target.value);setQuery('');setStatus('all');setPage(1)}}>{data.jobs.map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></div><p>Uma lista organizada por você para aprofundar a avaliação. Marcar um perfil não confirma interesse, disponibilidade nem seleção.</p></div>
 <section className="panel shortlist-toolbar"><div><label className="field-label" htmlFor="shortlist-query">Buscar na lista de interesse</label><input id="shortlist-query" className="text-input" placeholder="Nome, cidade ou função…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></div><div><label className="field-label" htmlFor="shortlist-status">Etapa do candidato</label><select id="shortlist-status" className="text-input" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">Todas as etapas</option>{Object.entries(contactStatusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><p role="status">{filtered.length} de {items.length} {items.length===1?'perfil marcado nesta vaga':'perfis marcados nesta vaga'}</p></section>
 <div className="candidate-grid shortlist-grid">{filtered.slice((current-1)*24,current*24).map(i=>{const {candidate:c,record:r,analysis:a}=i;const found=a?.evidence.filter(e=>e.status==='encontrada')||[];const meeting=(r.appointments||[]).filter(ap=>appointmentActive(ap)&&appointmentEnd(ap)>now).sort((x,y)=>Date.parse(x.startsAt)-Date.parse(y.startsAt))[0];return <article className="candidate-card shortlist-card" key={c.id}><div className="shortlist-card-head"><Star size={20} fill="currentColor"/><span className="tag">{contactStatusLabels[r.status]}</span></div><h3>{c.name}</h3><p className="candidate-role">{c.role||'Função a confirmar'}</p><div className="candidate-meta"><MapPin size={14}/>{c.city||'Localização a confirmar'}</div><div className="shortlist-evidence"><strong>{a?`${found.length} de ${job.criteria.length} critérios com trechos`:'Ainda não comparado nesta vaga'}</strong><p>{found[0]?.quote||'Abra o perfil para revisar as experiências e os pontos a confirmar.'}</p><small>Trechos do currículo precisam de revisão de contexto.</small></div><div className="shortlist-details"><span>Interesse: {r.interest}</span><span>Disponibilidade: {r.availability||'Não confirmada'}</span>{r.status==='Não contatar'&&<span className="shortlist-warning">Não realizar abordagem nesta vaga.</span>}{meeting&&<span><Clock3 size={14}/>{brazilDate(meeting.startsAt,true)} (Brasília) · {meeting.status==='confirmada'?'Confirmada':'A confirmar'}</span>}{r.report.trim()&&<span><FileText size={14}/>{r.reportNeedsReview?'Parecer precisa de revisão':'Parecer salvo'}</span>}</div><div className="shortlist-actions"><Button variant="outline" onClick={()=>onOpen(c.id,'evidence')}>Ver perfil<ChevronRight size={14}/></Button><Button variant="outline" onClick={()=>onOpen(c.id,'contact')}>Contato e notas</Button><Button variant="outline" onClick={()=>onOpen(c.id,'interview')}>Entrevista</Button>{r.report.trim()&&<Button variant="outline" onClick={()=>onOpen(c.id,'report')}>Abrir parecer</Button>}<Button variant="ghost" disabled={busy} aria-label={`Remover ${c.name} da lista de interesse`} onClick={()=>onRemove(c.id)}>Remover da lista</Button></div></article>})}</div>
 {!filtered.length&&<section className="panel empty-panel"><Users size={28}/><h2>{items.length?'Nenhum perfil nesta busca.':'Separe os perfis que deseja conhecer melhor.'}</h2><p>{items.length?'Ajuste a busca ou a etapa para ver outros perfis.':'No banco de talentos, use a estrela para adicionar candidatos à lista desta vaga.'}</p><Button variant="outline" onClick={items.length?()=>{setQuery('');setStatus('all');setPage(1)}:onExplore}>{items.length?'Limpar busca':'Explorar banco de talentos'}</Button></section>}
 {filtered.length>24&&<nav className="candidate-pagination" aria-label="Páginas da lista de interesse"><span>Página {current} de {pages}</span><div><Button variant="outline" disabled={current===1} onClick={()=>setPage(current-1)}>Anterior</Button><Button variant="outline" disabled={current===pages} onClick={()=>setPage(current+1)}>Próxima</Button></div></nav>}
 <p className="muted shortlist-footnote">As marcações são privadas e independentes para cada vaga. A decisão continua sendo sua.</p></>;
}
