'use client';
import {useMemo,useState} from 'react';
import {Copy,FileText,History,LoaderCircle,ShieldCheck} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {duplicatePairs,preservedVersions,defaultMergeChoices,mergeFields,mergeFieldLabels,type MergeChoices,type DuplicatePair} from '@/lib/candidate-duplicates';
import type {Candidate,Data,RecordData,Analysis} from '@/lib/domain';
import {brazilDate} from '@/lib/pt-br';

export default function CandidateDuplicates({data,onData}:{data:Data;onData:(data:Data)=>void}){
 const [query,setQuery]=useState(''),[pair,setPair]=useState<DuplicatePair|null>(null),[principal,setPrincipal]=useState(''),[choices,setChoices]=useState<MergeChoices>(defaultMergeChoices),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[restore,setRestore]=useState<Candidate|null>(null),[page,setPage]=useState(1);
 const found=useMemo(()=>duplicatePairs(data.candidates,query),[data.candidates,query]);
 const archived=data.archivedCandidates||[],history=data.candidates.filter(c=>archived.some(a=>a.mergedInto===c.id)||Boolean(c.mergeHistory?.length));
 const pages=Math.max(1,Math.ceil(found.pairs.length/12)),currentPage=Math.min(page,pages);
 const primary=pair?(pair.first.id===principal?pair.first:pair.second):null,secondary=pair?(pair.first.id===principal?pair.second:pair.first):null;
 function compare(item:DuplicatePair){setPair(item);setPrincipal((item.second.mergeHistory?.length||archived.some(c=>c.mergedInto===item.second.id))?item.second.id:item.first.id);setChoices({...defaultMergeChoices});setConfirmed(false)}
 async function change(body:unknown,method='POST'){
  setBusy(true);try{const response=await fetch('/api/candidates/merge',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error||'Não foi possível salvar.');onData(result);setPair(null);setRestore(null);toast.success(method==='PATCH'?'Cadastro restaurado.':'Cadastros reunidos. Currículos e históricos preservados.')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}
 }
 function versions(candidate:Candidate){return preservedVersions(data,candidate)}
 function originalHistory(candidate:Candidate,recordSnapshot?:RecordData[],analysisSnapshot?:{jobId:string;analysis:Analysis}[]){const records=recordSnapshot||data.records.filter(r=>r.candidateId===candidate.id);return <div className="duplicate-original-history"><h4>Currículo preservado</h4><p>{candidate.source} · {brazilDate(candidate.updated)}</p>{candidate.fileKey&&<a href={`/api/files/${recordSnapshot?(candidate.cvSourceId||candidate.id):candidate.id}?original=1`} target="_blank" rel="noreferrer">Abrir PDF original</a>}<pre>{recordSnapshot?candidate.text:candidate.originalText||candidate.text}</pre>{analysisSnapshot?.map(item=><details key={item.jobId}><summary>Comparação anterior · {data.jobs.find(j=>j.id===item.jobId)?.title||'Vaga anterior'}</summary>{item.analysis.evidence.map(e=><div key={e.criterionId}><pre>{e.quote||'A confirmar'}</pre><p>{e.explanation}</p></div>)}</details>)}{records.map(r=><details key={r.jobId}><summary>{data.jobs.find(j=>j.id===r.jobId)?.title||'Vaga anterior'} · {r.status}</summary><p>Interesse: {r.interest} · Disponibilidade: {r.availability}</p>{r.notes&&<><h4>Notas</h4><pre>{r.notes}</pre></>}{r.interview&&<><h4>Entrevista</h4>{r.interview.items.map(i=><div key={i.id}><strong>{i.question}</strong><pre>{i.answer||'Sem resposta registrada'}</pre><pre>{i.observation}</pre></div>)}</>}{r.appointments?.map(a=><p key={a.id}>{new Date(a.startsAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} (Brasília) · {a.status} · {a.format} · {a.location} · {a.notes}</p>)}{r.invitation&&<><h4>Rascunhos anteriores</h4><pre>{r.invitation.subject}\n{r.invitation.emailBody}\n{r.invitation.message}</pre></>}{r.report&&<><h4>Parecer anterior</h4><pre>{r.report}</pre></>}{r.events.length>0&&<><h4>Histórico</h4>{r.events.map((e,i)=><p key={i}>{brazilDate(e.at)} · {e.text}</p>)}</>}</details>)}</div>}
 return <>
 <section className="panel duplicate-panel"><div className="section-header"><div><h2><Copy size={22}/>Possíveis duplicados</h2><p>Confira os dados antes de reunir cadastros. Nome, telefone ou e-mail iguais são sinais para revisão.</p></div></div>
 <div className="notice"><ShieldCheck size={17}/>Nenhum perfil é reunido automaticamente. Telefones podem ser compartilhados e pessoas diferentes podem ter o mesmo nome.</div>
 <label className="field-label" htmlFor="duplicates-query">Buscar nas sugestões</label><input id="duplicates-query" className="text-input" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Nome, e-mail ou telefone"/>
 <p className="import-help">{found.pairs.length} {found.pairs.length===1?'sugestão':'sugestões'}{found.limited?' exibidas. Há mais resultados; refine a busca.':'.'} A busca usa os cadastros ativos da sua base e não faz chamadas à IA.</p>
 <div className="duplicate-list">{found.pairs.slice((currentPage-1)*12,currentPage*12).map(item=><article className="duplicate-suggestion" key={`${item.first.id}:${item.second.id}`}><div><strong>{item.first.name}</strong><span>{item.first.source}</span></div><div><strong>{item.second.name}</strong><span>{item.second.source}</span></div><div className="duplicate-reasons">{item.reasons.map(reason=><span className="tag" key={reason}>{reason}</span>)}{item.reasons.length===1&&item.reasons[0]==='Nome completo igual'&&<small>O nome sozinho não confirma identidade.</small>}</div><Button variant="outline" onClick={()=>compare(item)}>Comparar cadastros</Button></article>)}</div>
 {!found.pairs.length&&<div className="empty-panel"><Copy size={26}/><h3>Nenhuma sugestão encontrada.</h3><p>{query?'Tente outro termo.':'Novos currículos também serão verificados quando entrarem na base.'}</p></div>}
 {pages>1&&<nav className="candidate-pagination" aria-label="Páginas de duplicados"><Button variant="outline" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Anterior</Button><span>Página {currentPage} de {pages}</span><Button variant="outline" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Próxima</Button></nav>}
 </section>
 <section className="panel duplicate-panel"><h2><History size={22}/>Currículos e históricos preservados</h2><p>Os cadastros reunidos saem da busca, mas seus arquivos e registros anteriores continuam aqui.</p>{!history.length&&<p className="import-help">Nenhum cadastro reunido até agora.</p>}{history.filter(c=>!query||c.name.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))).map(c=><details className="duplicate-version-group" key={c.id}><summary>{c.name} · {versions(c).length} {versions(c).length===1?'cadastro preservado':'cadastros preservados'}</summary>{versions(c).map(version=><details className="duplicate-version" key={version.id}><summary><FileText size={16}/>{version.source} · {version.id===(c.cvSourceId||c.id)?'Currículo em uso':'Versão preservada'}</summary>{originalHistory(version)}{version.mergedInto&&<Button variant="outline" disabled={busy} onClick={()=>setRestore(version)}>Restaurar cadastro separado</Button>}</details>)}{c.mergeHistory?.map((snapshot,i)=><details className="duplicate-version" key={`${snapshot.at}:${i}`}><summary>Dados do principal antes da união · {brazilDate(snapshot.at)}</summary><p>{snapshot.candidate.name} · {snapshot.candidate.phone||'Telefone não informado'} · {snapshot.candidate.email||'E-mail não informado'} · {snapshot.candidate.city} · {snapshot.candidate.role}</p>{originalHistory(snapshot.candidate,snapshot.records,snapshot.analyses)}</details>)}</details>)}</section>
 <Dialog open={Boolean(pair)} onOpenChange={open=>{if(!open&&!busy)setPair(null)}}><DialogContent className="duplicate-dialog"><DialogHeader><DialogTitle>Compare antes de reunir</DialogTitle><DialogDescription>Escolha o cadastro principal e revise cada dado. Ambos os originais serão preservados.</DialogDescription></DialogHeader>{pair&&primary&&secondary&&<><div className="duplicate-side-by-side">{[pair.first,pair.second].map(c=><section key={c.id}><label><input type="radio" name="principal" checked={principal===c.id} disabled={busy||Boolean((c.id===pair.first.id?pair.second:pair.first).mergeHistory?.length)||archived.some(a=>a.mergedInto===(c.id===pair.first.id?pair.second.id:pair.first.id))} onChange={()=>{setPrincipal(c.id);setChoices({...defaultMergeChoices});setConfirmed(false)}}/>Manter como principal</label><h3>{c.name}</h3><p>{c.source} · {brazilDate(c.updated)}</p><p>{c.role||'Cargo não informado'} · {c.city||'Localização não informada'}</p><p>{c.phone||'Telefone não informado'}</p><p>{c.email||'E-mail não informado'}</p><details><summary>Experiências do currículo</summary><pre>{c.text}</pre></details><p>{data.records.filter(r=>r.candidateId===c.id).length} {data.records.filter(r=>r.candidateId===c.id).length===1?'registro de vaga':'registros de vagas'}</p></section>)}</div>
 <h3>Dados que ficarão no cadastro principal</h3>{mergeFields.map(field=><label className="duplicate-field" key={field}><span>{mergeFieldLabels[field]}</span><select className="text-input" aria-label={`Manter ${mergeFieldLabels[field].toLowerCase()}`} value={choices[field]} disabled={busy} onChange={e=>{setChoices({...choices,[field]:e.target.value as 'primary'|'secondary'});setConfirmed(false)}}><option value="primary">Principal · {field==='text'?primary.source:primary[field]||'Não informado'}</option><option value="secondary">Outro cadastro · {field==='text'?secondary.source:secondary[field]||'Não informado'}</option></select></label>)}
 <p className="import-help">Notas, entrevistas, agendamentos e pareceres serão reunidos por vaga. Em conflitos, mantém-se o registro principal e o outro permanece no histórico preservado. “Não contatar” prevalece. Pareceres exigirão revisão e a comparação com a vaga precisará ser refeita. Trocar dados não confirma telefone, e-mail ou localização.</p>
 <label className="duplicate-confirm"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>Conferi os dados e confirmo que estes cadastros são da mesma pessoa.</label><Button className="primary-button" disabled={!confirmed||busy} onClick={()=>void change({primaryId:primary.id,secondaryId:secondary.id,choices,confirmed:true,version:data.version})}>{busy?<LoaderCircle className="spin" size={16}/>:<Copy size={16}/>}Reunir cadastros</Button></>}</DialogContent></Dialog>
 <Dialog open={Boolean(restore)} onOpenChange={open=>{if(!open&&!busy)setRestore(null)}}><DialogContent><DialogHeader><DialogTitle>Restaurar cadastro separado</DialogTitle><DialogDescription>O cadastro original voltará à busca com seu histórico anterior. Os registros já reunidos no principal serão mantidos; revise-os se necessário.</DialogDescription></DialogHeader><p>{restore?.name} · {restore?.source}</p><Button disabled={busy} onClick={()=>void change({candidateId:restore?.id,version:data.version},'PATCH')}>Confirmar restauração</Button></DialogContent></Dialog>
 </>;
}
