'use client';
import {useState} from 'react';
import {Star,Mail,LoaderCircle} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Candidate,RecordData} from '@/lib/domain';
import {emptyInvitation,generateInvitation} from '@/lib/interview-invitation';
import type {BatchAction,BatchSettings,BatchSummary} from '@/lib/candidate-batch';

export default function CandidateBatch({candidates,page,selected,records,jobId,jobTitle,disabled,onSelect,onApply}:{candidates:Candidate[];page:Candidate[];selected:string[];records:RecordData[];jobId:string;jobTitle:string;disabled:boolean;onSelect:(ids:string[])=>void;onApply:(action:BatchAction,settings?:BatchSettings)=>Promise<BatchSummary>}){
 const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[previewId,setPreviewId]=useState('');
 const [settings,setSettings]=useState<BatchSettings>({recruiter:'',company:'',roleTitle:jobTitle,instructions:''});
 const profiles=candidates.filter(c=>selected.includes(c.id));
 const eligible=profiles.filter(c=>{const r=records.find(r=>r.candidateId===c.id&&r.jobId===jobId);return r?.status!=='Não contatar'&&!r?.invitation;});
 const blocked=profiles.filter(c=>records.some(r=>r.candidateId===c.id&&r.jobId===jobId&&r.status==='Não contatar')).length;
 const existing=profiles.length-eligible.length-blocked;
 const candidate=eligible.find(c=>c.id===previewId)||eligible[0];
 let preview;try{if(candidate)preview=generateInvitation(candidate.name,{...emptyInvitation(settings.roleTitle),...settings});}catch{}
 async function apply(action:BatchAction){setSaving(true);try{const result=await onApply(action,action==='invitations'?settings:undefined);toast.success(action==='shortlist'?`${result.changed} perfis adicionados à lista de interesse. ${result.existing} já estavam na lista.`:`${result.changed} rascunhos salvos. ${result.existing} convites existentes preservados; ${result.blocked} contatos bloqueados ignorados. Nenhuma mensagem enviada.`);setOpen(false);}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 return <><section className="batch-toolbar" aria-label="Ações em lote"><div><strong>{selected.length?`${selected.length} selecionados`:'Selecione perfis para trabalhar em lote'}</strong><small>Vaga: {jobTitle} · Até 100 perfis por vez</small></div><div className="batch-actions"><Button variant="outline" disabled={disabled||saving||!page.length} onClick={()=>{const ids=Array.from(new Set([...selected,...page.map(c=>c.id)]));if(ids.length>100){toast.error('Esta página ultrapassa o limite de 100 selecionados. Ajuste a seleção.');return;}onSelect(ids);}}>Selecionar esta página</Button><Button variant="outline" disabled={disabled||saving||!candidates.length||candidates.length>100} onClick={()=>onSelect(candidates.map(c=>c.id))}>Selecionar filtrados ({candidates.length})</Button>{selected.length>0&&<><Button variant="ghost" disabled={disabled||saving} onClick={()=>onSelect([])}>Limpar seleção</Button><Button variant="outline" disabled={disabled||saving} onClick={()=>void apply('shortlist')}>{saving?<LoaderCircle size={16} className="spin"/>:<Star size={16}/>}Adicionar à lista</Button><Button className="primary-button" disabled={disabled||saving} onClick={()=>{setSettings(s=>({...s,roleTitle:jobTitle}));setOpen(true);}}><Mail size={16}/>Preparar convites</Button></>}</div></section>
 <Dialog open={open} onOpenChange={value=>{if(!saving)setOpen(value);}}><DialogContent className="batch-dialog"><DialogHeader><DialogTitle>Convites para os perfis selecionados</DialogTitle><DialogDescription>Prepare rascunhos individuais para {jobTitle}. Nenhum e-mail ou WhatsApp será enviado.</DialogDescription></DialogHeader><div className="notice">{eligible.length} rascunhos novos · {existing} convites existentes serão preservados · {blocked} contatos marcados como “Não contatar” serão ignorados.</div><div className="invitation-fields"><label>Seu nome<input className="text-input" maxLength={200} value={settings.recruiter} onChange={e=>setSettings(s=>({...s,recruiter:e.target.value}))}/></label><label>Empresa (opcional)<input className="text-input" maxLength={200} value={settings.company} onChange={e=>setSettings(s=>({...s,company:e.target.value}))}/></label><label>Nome da vaga no convite<input className="text-input" maxLength={200} value={settings.roleTitle} onChange={e=>setSettings(s=>({...s,roleTitle:e.target.value}))}/></label></div><label className="field-label">Orientações em comum (opcional)<textarea className="text-input" maxLength={2000} value={settings.instructions} onChange={e=>setSettings(s=>({...s,instructions:e.target.value}))}/></label><p className="muted">Dia, horário e formato serão combinados individualmente. Depois de salvar, abra o perfil em “Convite” para editar e copiar cada texto.</p>{candidate&&<section className="batch-preview"><label>Revisar rascunho de<select className="text-input" value={candidate.id} onChange={e=>setPreviewId(e.target.value)}>{eligible.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p className="muted">E-mail: {candidate.email||'a confirmar'} · Telefone: {candidate.phone||'a confirmar'}. Dados declarados no cadastro.</p>{preview?<><h3>{preview.subject}</h3><pre>{preview.emailBody}</pre><details><summary>Ver mensagem de WhatsApp</summary><pre>{preview.message}</pre></details></>:<p>Preencha seu nome e o nome da vaga para revisar os textos.</p>}</section>}<div className="dialog-actions"><Button variant="outline" disabled={saving} onClick={()=>setOpen(false)}>Cancelar</Button><Button className="primary-button" disabled={disabled||saving||!preview||!eligible.length} onClick={()=>void apply('invitations')}>{saving&&<LoaderCircle size={16} className="spin"/>}Salvar {eligible.length} rascunhos</Button></div></DialogContent></Dialog></>;
}
