'use client';
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import type {RecordData} from '@/lib/domain';
import {followUpMessage,waitingDays} from '@/lib/contact-follow-up';
import {brazilDate} from '@/lib/pt-br';
export default function ContactFollowUp({record,name,jobTitle,busy,onSave}:{record:RecordData;name:string;jobTitle:string;busy:boolean;onSave:(action:'schedule'|'complete'|'cancel',date:string,note:string)=>Promise<void>}){
 const [date,setDate]=useState(record.followUp?.date||''),[note,setNote]=useState(record.followUp?.note||''),[recruiter,setRecruiter]=useState(record.invitation?.recruiter||''),[company,setCompany]=useState(record.invitation?.company||''),[message,setMessage]=useState(''),[working,setWorking]=useState(false);
 const [now,setNow]=useState(()=>Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer);},[]);
 const blocked=['Não contatar','Encerrado','Selecionado'].includes(record.status),pending=record.followUp&&!record.followUp.completedAt,days=waitingDays(record,now);
 async function save(action:'schedule'|'complete'|'cancel'){setWorking(true);try{await onSave(action,date,note);if(action==='cancel'){setDate('');setNote('');}toast.success(action==='schedule'?'Próximo contato salvo.':action==='complete'?'Contato manual registrado. Lembrete concluído.':'Lembrete cancelado.');}catch(e){toast.error((e as Error).message);}finally{setWorking(false);}}
 return <section className="follow-up-editor"><h3>Próximo contato</h3><p className="muted">Lembrete interno desta vaga. Nenhuma mensagem será enviada.</p>{record.status==='Contato realizado'&&<p className="muted">{days===null?'Data do último contato a confirmar.':`Aguardando retorno há ${days} ${days===1?'dia':'dias'}, desde o último contato registrado.`}</p>}{blocked&&<div className="notice">Processo encerrado ou marcado como “Não contatar”. Novos lembretes e mensagens estão bloqueados.</div>}<label>Data do próximo contato<input aria-label="Data do próximo contato" className="text-input" type="date" value={date} disabled={blocked||working} onChange={e=>setDate(e.target.value)}/></label><label>Observação do lembrete<textarea className="text-input" maxLength={2000} value={note} disabled={blocked||working} onChange={e=>setNote(e.target.value)} placeholder="Ex.: confirmar interesse e disponibilidade para conversar."/></label><div className="follow-up-actions"><Button variant="outline" disabled={busy||working||blocked||!date} onClick={()=>void save('schedule')}>{pending?'Atualizar lembrete':'Salvar próximo contato'}</Button>{pending&&<><Button variant="outline" disabled={busy||working||blocked} onClick={()=>void save('complete')}>Já fiz este contato</Button><Button variant="ghost" disabled={busy||working} onClick={()=>void save('cancel')}>Cancelar lembrete</Button></>}</div>{record.followUp?.completedAt&&<p className="muted">Último lembrete concluído em {brazilDate(record.followUp.completedAt,true)} (Brasília).</p>}<h3>Rascunho de WhatsApp</h3><label>Seu nome no lembrete<input className="text-input" maxLength={200} value={recruiter} onChange={e=>setRecruiter(e.target.value)} disabled={blocked}/></label><label>Empresa no lembrete (opcional)<input className="text-input" maxLength={200} value={company} onChange={e=>setCompany(e.target.value)} disabled={blocked}/></label><Button variant="outline" disabled={blocked||working||busy||!recruiter.trim()} onClick={()=>{try{setMessage(followUpMessage(name,jobTitle,recruiter,company,record.status));}catch(e){toast.error((e as Error).message);}}}>Preparar lembrete para revisar</Button>{message&&!blocked&&<><label>Mensagem para revisar<textarea className="notes-input" rows={6} maxLength={6000} value={message} onChange={e=>setMessage(e.target.value)}/></label><Button variant="outline" onClick={()=>void navigator.clipboard.writeText(message).then(()=>toast.success('Rascunho copiado. Revise antes de enviar.')).catch(()=>toast.error('Não foi possível copiar. Selecione o texto manualmente.'))}>Copiar lembrete</Button><p className="muted">O rascunho fica nesta tela. Copiar não registra contato nem conclui o lembrete.</p></>}</section>;
}
