'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import type {Data} from '@/lib/domain';
import {followUpItems,waitingDays} from '@/lib/contact-follow-up';
export default function FollowUpList({data,jobId,now,onProfile}:{data:Data;jobId:string;now:number;onProfile:(candidateId:string,jobId:string,tab:string)=>void}){
 const [scope,setScope]=useState('due'),[page,setPage]=useState(1),items=followUpItems(data,jobId,now),due=items.filter(i=>i.due),shown=scope==='all'?items:due,pages=Math.max(1,Math.ceil(shown.length/8)),current=Math.min(page,pages);
 return <section className="panel follow-up-list"><div className="section-header"><div><h2>Contatos para retomar</h2><p className="muted">Pendências para hoje ou em atraso: {due.length} · Datas de Brasília</p></div><Button variant="outline" onClick={()=>{setScope(scope==='all'?'due':'all');setPage(1);}}>{scope==='all'?'Ver pendências do dia':'Ver também próximos dias'}</Button></div>{shown.slice((current-1)*8,current*8).map(i=>{const days=waitingDays(i.record,now);return <article key={`${i.job.id}:${i.candidate.id}`} className="follow-up-item"><div><strong>{i.candidate.name}</strong><p>{i.job.title}</p><span className={`tag ${i.overdue?'follow-up-overdue':''}`}>{i.overdue?'Em atraso · ':i.due?'Hoje · ':'Próximo contato · '}{i.record.followUp!.date.split('-').reverse().join('/')}</span>{i.record.followUp!.note&&<p>{i.record.followUp!.note}</p>}{i.record.status==='Contato realizado'&&<small>{days===null?'Data do último contato a confirmar':`Aguardando retorno há ${days} ${days===1?'dia':'dias'}`}</small>}</div><Button variant="outline" onClick={()=>onProfile(i.candidate.id,i.job.id,'contact')}>Revisar contato</Button></article>;})}{!shown.length&&<p className="muted">{scope==='all'?'Nenhum próximo contato pendente nesta seleção.':'Nenhum contato pendente para hoje ou em atraso. Você pode consultar os próximos dias.'}</p>}{pages>1&&<nav className="candidate-pagination" aria-label="Páginas dos próximos contatos"><span>Página {current} de {pages}</span><div><Button variant="outline" disabled={current===1} onClick={()=>setPage(current-1)}>Anterior</Button><Button variant="outline" disabled={current===pages} onClick={()=>setPage(current+1)}>Próxima</Button></div></nav>}</section>;
}
