'use client';
import {useState} from 'react';
import {ClipboardList,Save,Copy,LoaderCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {toast} from 'sonner';
import type {Candidate,Job} from '@/lib/domain';
import {prepareInterviewGuide,interviewItemCurrent,interviewSummary,type InterviewGuide as Guide,type InterviewItem} from '@/lib/interview-guide';
import {brazilDate} from '@/lib/pt-br';
export default function InterviewGuide({candidate,job,saved,onSave}:{candidate:Candidate;job:Job;saved?:Guide;onSave:(guide:Guide)=>Promise<void>}){
 const [draft,setDraft]=useState<Guide|undefined>(()=>saved?structuredClone(saved):undefined),[snapshot,setSnapshot]=useState(()=>JSON.stringify(saved)),[busy,setBusy]=useState(false);
 const dirty=JSON.stringify(draft)!==snapshot;
 const stale=draft&&(draft.candidateRevision!==(candidate.editedAt||candidate.updated)||job.criteria.some(c=>!draft.items.some(i=>i.criterionId===c.id&&i.criterionText===c.text&&i.kind===c.kind)));
 const answered=draft?.items.filter(i=>i.answer.trim()).length||0;
 function prepare(){try{setDraft(prepareInterviewGuide(candidate,job,draft,new Date().toISOString()));toast.success('Roteiro preparado. Perguntas e respostas anteriores foram preservadas.')}catch(e){toast.error((e as Error).message)}}
 function edit(id:string,key:'question'|'answer'|'observation',value:string){setDraft(d=>d?{...d,items:d.items.map(i=>i.id===id?{...i,[key]:value}:i)}:d)}
 async function save(){if(!draft)return;setBusy(true);try{const next={...draft,updated:new Date().toISOString()};await onSave(next);setDraft(next);setSnapshot(JSON.stringify(next));toast.success('Roteiro e respostas salvos nesta vaga.')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(interviewSummary(draft,job));toast.success('Registros copiados para sua revisão.')}catch{toast.error('Não foi possível copiar os registros.')}}
 function itemCard(item:InterviewItem,index:number){const current=interviewItemCurrent(item,job),evidence=job.analyses.find(a=>a.candidateId===candidate.id)?.evidence.find(e=>e.criterionId===item.criterionId);return <section className={`interview-question ${current?'':'interview-previous'}`} key={item.id}><div className="interview-question-heading"><span>{index+1}</span><div><h4>{item.criterionText}</h4><small>{!current?'Critério alterado ou removido · Registro anterior':item.kind==='geral'?'Conversa sobre a oportunidade':item.kind==='entrevista'?'Explorar exemplos na conversa':evidence?.status==='encontrada'?'Aprofundar a experiência declarada':'Ponto a confirmar'}</small></div></div>{current&&evidence?.quote&&<details><summary>Ver trecho do currículo para contexto</summary><blockquote>{evidence.quote}</blockquote></details>}<label className="field-label" htmlFor={`question-${item.id}`}>Pergunta {index+1}</label><textarea className="notes-input" id={`question-${item.id}`} rows={3} maxLength={3000} value={item.question} disabled={busy} onChange={e=>edit(item.id,'question',e.target.value)}/><label className="field-label" htmlFor={`answer-${item.id}`}>Resposta registrada {index+1}</label><textarea className="notes-input" id={`answer-${item.id}`} rows={4} maxLength={4000} value={item.answer} disabled={busy} onChange={e=>edit(item.id,'answer',e.target.value)} placeholder="Registre o que a pessoa declarou, com exemplos. Se ainda não conversaram, deixe em branco."/><label className="field-label" htmlFor={`observation-${item.id}`}>Observação da recrutadora {index+1}</label><textarea className="notes-input" id={`observation-${item.id}`} rows={2} maxLength={2000} value={item.observation} disabled={busy} onChange={e=>edit(item.id,'observation',e.target.value)} placeholder="Suas observações e pontos para aprofundar."/></section>}
 return <section className="interview-section"><div className="invitation-heading"><ClipboardList size={21}/><div><h3>Uma entrevista com contexto.</h3><p>{job.title} · {candidate.name}</p></div></div><p className="muted">O roteiro aproveita as perguntas da análise e organiza os critérios a confirmar. Você pode editar cada pergunta antes da conversa. Nenhuma nova consulta à IA é necessária.</p>{stale&&<div className="notice">O cadastro ou os critérios mudaram. Revise o roteiro. Atualizar acrescenta novos critérios e preserva as perguntas e respostas anteriores.</div>}<div className="interview-actions"><Button variant="outline" disabled={busy||!job.criteria.length} onClick={prepare}><ClipboardList size={16}/>{draft?'Atualizar roteiro sem apagar respostas':'Preparar roteiro'}</Button>{draft&&<Button variant="outline" disabled={!interviewSummary(draft)||busy} onClick={copy}><Copy size={16}/>Copiar registros</Button>}</div>{!job.criteria.length&&<div className="notice">Organize e revise os critérios da vaga para preparar as perguntas.</div>}{draft&&<><p className="interview-progress" role="status" aria-live="polite">{answered} de {draft.items.length} perguntas com resposta registrada</p>{draft.items.map(itemCard)}<div className="interview-save"><Button className="primary-button" disabled={busy||!dirty||!draft.items.length||draft.items.some(i=>!i.question.trim())} onClick={save}>{busy?<LoaderCircle size={16} className="spin"/>:<Save size={16}/>}Salvar roteiro e respostas</Button><span role="status">{dirty?'Alterações ainda não salvas.':draft.updated?`Salvo em ${brazilDate(draft.updated,true)} (Brasília).`:'Roteiro ainda não salvo.'}</span></div></>}<p className="muted">Salvar não altera a etapa, o interesse, a disponibilidade nem a análise do currículo. As respostas salvas entram em novos rascunhos de parecer como registros da entrevista. Salve antes de fechar este perfil.</p></section>;
}
