'use client';
import {useEffect,useMemo,useState} from 'react';
import FollowUpList from './follow-up-list';
import {Users,Clock3,FileText,CalendarDays,ChevronRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {Data} from '@/lib/domain';
import {recruitmentOverview} from '@/lib/recruitment-overview';
import {contactStatusLabels} from '@/lib/contact-board';
import {brazilDate} from '@/lib/pt-br';
export default function RecruitmentOverview({data,jobId,onJob,onProfile,onAgenda,onCandidates}:{data:Data;jobId:string;onJob:(id:string)=>void;onProfile:(candidateId:string,jobId:string,tab:string)=>void;onAgenda:()=>void;onCandidates:()=>void}){
 const [scope,setScope]=useState(jobId),[filter,setFilter]=useState('all'),[page,setPage]=useState(1),[now,setNow]=useState(()=>Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer)},[]);
 const selectedScope=scope==='all'||data.jobs.some(j=>j.id===scope)?scope:jobId;
 const overview=useMemo(()=>recruitmentOverview(data,selectedScope,now),[data,selectedScope,now]);
 const filtered=overview.items.filter(i=>filter==='all'||(filter==='review'?i.record.report.trim()&&i.record.reportNeedsReview:i.record.status===filter));
 const pages=Math.max(1,Math.ceil(filtered.length/12)),current=Math.min(page,pages);
 function choose(value:string){setFilter(value);setPage(1)}
 return <><div className="overview-scope"><div><label className="field-label" htmlFor="overview-job">Acompanhamento da vaga</label><select className="text-input" id="overview-job" value={selectedScope} onChange={e=>{setScope(e.target.value);choose('all');if(e.target.value!=='all')onJob(e.target.value)}}><option value="all">Todas as vagas</option>{data.jobs.map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></div><p>Entram no painel os candidatos comparados ou com registros na vaga. Uma pessoa pode participar de mais de um processo.</p></div>
 <div className="agenda-reminders overview-metrics">{[{label:'Pessoas acompanhadas',count:overview.people,icon:Users,action:()=>choose('all')},{label:'Aguardando retorno',count:overview.waiting.length,icon:Clock3,action:()=>choose('Contato realizado')},{label:'Pareceres para revisar',count:overview.review.length,icon:FileText,action:()=>choose('review')},{label:'Entrevistas sem conclusão',count:overview.overdue.length,icon:CalendarDays,action:onAgenda}].map(c=><button className="agenda-reminder" key={c.label} onClick={c.action}><c.icon size={19}/><strong>{c.count}</strong><span>{c.label}</span></button>)}</div>
 <FollowUpList key={selectedScope} data={data} jobId={selectedScope} now={now} onProfile={onProfile}/><section className="panel overview-stages"><h2>Etapas dos processos</h2><p className="muted">As etapas são registradas por você. Agendar uma entrevista não altera a etapa automaticamente.</p><div className="overview-stage-grid">{Object.entries(contactStatusLabels).map(([status,label])=><button key={status} className={filter===status?'selected':''} aria-pressed={filter===status} onClick={()=>choose(filter===status?'all':status)}><strong>{overview.items.filter(i=>i.record.status===status).length}</strong><span>{label}</span></button>)}</div></section>
 <div className="overview-columns"><section className="panel overview-processes"><div className="section-header"><div><h2>{filter==='review'?'Pareceres que precisam de revisão':filter==='all'?'Candidatos acompanhados':contactStatusLabels[filter]}</h2><p className="muted" role="status">{filtered.length} {filtered.length===1?'participação em vaga':'participações em vagas'} · {overview.reports.length} {overview.reports.length===1?'parecer salvo':'pareceres salvos'}</p></div>{filter!=='all'&&<Button variant="ghost" onClick={()=>choose('all')}>Ver todas as etapas</Button>}</div>
 {filtered.slice((current-1)*12,current*12).map(i=><article className="overview-person" key={`${i.job.id}:${i.candidate.id}`}><div><h3>{i.candidate.name}</h3><p>{i.job.title}</p><span className="tag">{contactStatusLabels[i.record.status]||i.record.status}</span>{i.record.report.trim()&&i.record.reportNeedsReview&&<small>Parecer precisa de revisão</small>}</div><Button variant="outline" onClick={()=>onProfile(i.candidate.id,i.job.id,filter==='review'?'report':'contact')}>{filter==='review'?'Revisar parecer':'Abrir acompanhamento'}<ChevronRight size={15}/></Button></article>)}
 {!filtered.length&&<div className="empty-panel"><Users size={28}/><h3>{overview.items.length?'Nenhum candidato nesta etapa.':'Seu acompanhamento começa aqui.'}</h3><p>{overview.items.length?'Escolha outra etapa para continuar.':'Compare candidatos na vaga ou registre uma conversa para vê-los aqui.'}</p><Button variant="outline" onClick={overview.items.length?()=>choose('all'):onCandidates}>{overview.items.length?'Ver todas as etapas':'Explorar banco de talentos'}</Button></div>}
 {filtered.length>12&&<nav className="candidate-pagination" aria-label="Páginas do acompanhamento"><span>Página {current} de {pages}</span><div><Button variant="outline" disabled={current===1} onClick={()=>setPage(current-1)}>Anterior</Button><Button variant="outline" disabled={current===pages} onClick={()=>setPage(current+1)}>Próxima</Button></div></nav>}</section>
 <section className="panel overview-meetings"><h2>Próximas entrevistas</h2><p className="muted">{overview.upcoming.length} {overview.upcoming.length===1?'encontro':'encontros'} · Horários de Brasília</p>{overview.upcoming.slice(0,6).map(i=><article key={i.appointment.id}><strong>{i.candidate.name}</strong><p>{i.job.title}</p><span>{brazilDate(i.appointment.startsAt,true)} (Brasília)</span><small>{i.appointment.status==='confirmada'?'Confirmada':'A confirmar'}</small><Button variant="ghost" onClick={()=>onProfile(i.candidate.id,i.job.id,'interview')}>Abrir roteiro<ChevronRight size={15}/></Button></article>)}{!overview.upcoming.length&&<p className="overview-no-meeting">Nenhuma entrevista futura registrada nesta seleção.</p>}<Button variant="outline" onClick={onAgenda}>Ver agenda completa</Button></section></div></>;
}
