'use client';
import {useMemo,useState} from 'react';
import {ChevronLeft,ChevronRight,CalendarDays,Clock3,MapPin} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {calendarWeek,calendarDay,calendarSegments,calendarHours,calendarTime} from '@/lib/weekly-calendar';
import {brazilParts,appointmentEnd,appointmentLabels,appointmentFormats,type AgendaItem} from '@/lib/interview-agenda';
import {brazilDate} from '@/lib/pt-br';
import CalendarExport from './calendar-export';
export default function WeeklyCalendar({items,now,onEdit,onProfile}:{items:AgendaItem[];now:number;onEdit:(item:AgendaItem)=>void;onProfile:(candidateId:string,jobId:string)=>void}){
 const today=brazilParts(new Date(now).toISOString()),[anchor,setAnchor]=useState(today.date),[selectedId,setSelectedId]=useState<string|null>(null);
 const days=calendarWeek(anchor),segments=useMemo(()=>calendarSegments(items,calendarWeek(anchor)),[items,anchor]),hours=calendarHours(segments);
 const selected=items.find(i=>i.appointment.id===selectedId),count=new Set(segments.map(s=>s.item.appointment.id)).size;
 const dayLabel=(date:string)=>new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC',weekday:'short'}).format(new Date(`${date}T12:00:00Z`));
 const nowMinute=Number(today.time.slice(0,2))*60+Number(today.time.slice(3,5)),height=(hours.end-hours.start)*60;
 return <section className="weekly-calendar" aria-label="Calendário semanal de entrevistas"><div className="weekly-toolbar"><div className="weekly-navigation"><Button variant="outline" aria-label="Semana anterior" onClick={()=>setAnchor(calendarDay(days[0],-7))}><ChevronLeft size={17}/></Button><Button variant="outline" aria-label="Próxima semana" onClick={()=>setAnchor(calendarDay(days[0],7))}><ChevronRight size={17}/></Button><Button variant="outline" onClick={()=>setAnchor(today.date)}>Esta semana</Button></div><h2>{brazilDate(`${days[0]}T12:00:00Z`)} — {brazilDate(`${days[6]}T12:00:00Z`)}</h2><div><label className="field-label" htmlFor="calendar-week-date">Ir para a semana de</label><input id="calendar-week-date" className="text-input" type="date" min="2000-01-01" max="2100-12-31" value={anchor} onChange={e=>{if(e.target.value&&e.target.validity.valid)setAnchor(e.target.value)}}/></div></div>
 <div className="weekly-summary"><p role="status">{count} {count===1?'entrevista nesta semana':'entrevistas nesta semana'} · Horários de Brasília</p><div className="weekly-legend" aria-label="Legenda das situações">{Object.entries(appointmentLabels).map(([status,label])=><span key={status}><i className={`weekly-dot status-${status}`} aria-hidden="true"/>{label}</span>)}</div></div>
 <div className="weekly-scroll" tabIndex={0} aria-label="Dias e horários da semana. Role para ver outros horários e dias."><div className="weekly-grid"><div className="weekly-days"><div className="weekly-zone">Brasília</div>{days.map(day=><div key={day} className={day===today.date?'weekly-day is-today':'weekly-day'}><span>{dayLabel(day)}</span><strong>{day.slice(8,10)}</strong><small>{day.slice(5,7)}/{day.slice(0,4)}</small></div>)}</div><div className="weekly-body" style={{height}}><div className="weekly-times">{Array.from({length:hours.end-hours.start},(_,i)=><span key={i} style={{top:i*60}}>{calendarTime((hours.start+i)*60)}</span>)}</div>{days.map(day=><div className={`weekly-column ${day===today.date?'is-today':''}`} key={day} aria-label={`${dayLabel(day)} ${brazilDate(`${day}T12:00:00Z`)}`}>{segments.filter(s=>s.date===day).map(s=>{const a=s.item.appointment;return <button key={a.id} className={`weekly-event status-${a.status} ${s.endMinute-s.startMinute<30?'is-short':''}`} style={{top:s.startMinute-hours.start*60,height:Math.max(22,s.endMinute-s.startMinute),left:`calc(${s.column/s.columns*100}% + 3px)`,width:`calc(${100/s.columns}% - 6px)`}} aria-label={`${s.item.candidate.name}, ${brazilDate(`${day}T12:00:00Z`)}, ${calendarTime(s.startMinute)} a ${calendarTime(s.endMinute)}, ${appointmentLabels[a.status]}`} title={`${s.item.candidate.name} · ${s.item.job.title} · ${calendarTime(s.startMinute)}–${calendarTime(s.endMinute)} · ${appointmentLabels[a.status]}`} onClick={()=>setSelectedId(a.id)}><span>{calendarTime(s.startMinute)}{s.continuesBefore?' · continuação':''}</span><strong>{s.item.candidate.name}</strong>{s.endMinute-s.startMinute>=60&&<small>{s.item.job.title}</small>}{s.continuesAfter&&<small>Continua no próximo dia</small>}</button>})}{day===today.date&&nowMinute>=hours.start*60&&nowMinute<hours.end*60&&<div className="weekly-now" style={{top:nowMinute-hours.start*60}} title={`Agora: ${today.time} (Brasília)`} aria-label={`Agora: ${today.time} (Brasília)`}/>}</div>)}</div></div></div>
 {!count&&<p className="weekly-empty">Nenhuma entrevista nesta semana com os filtros atuais. Navegue pelas semanas ou ajuste a busca.</p>}<div className="weekly-export"><div><h3>Sua semana em outro calendário</h3><p>Baixe os encontros confirmados ou a confirmar desta semana, respeitando os filtros acima.</p></div><CalendarExport key={anchor} items={items} anchor={anchor}/></div><p className="weekly-help">Clique em uma entrevista para ver os detalhes. Em telas menores, role o calendário para os lados.</p>
 <Dialog open={Boolean(selected)} onOpenChange={open=>{if(!open)setSelectedId(null)}}><DialogContent className="calendar-event-dialog">{selected&&<><DialogHeader><DialogTitle>{selected.candidate.name}</DialogTitle><DialogDescription>{selected.job.title}</DialogDescription></DialogHeader><span className={`weekly-detail-status status-${selected.appointment.status}`}>{appointmentLabels[selected.appointment.status]}</span><div className="agenda-card-info"><span><CalendarDays size={16}/>{brazilDate(selected.appointment.startsAt,true)} (Brasília)</span><span><Clock3 size={16}/>{selected.appointment.duration} minutos · até {brazilDate(new Date(appointmentEnd(selected.appointment)).toISOString(),true)} (Brasília)</span><span>{appointmentFormats[selected.appointment.format]}</span><span><MapPin size={16}/>{selected.appointment.location||'Local ou acesso a definir'}</span></div>{selected.appointment.notes&&<p className="agenda-notes">{selected.appointment.notes}</p>}<div className="agenda-card-actions"><Button variant="outline" onClick={()=>{setSelectedId(null);onEdit(selected)}}>Editar ou reagendar</Button><Button className="primary-button" onClick={()=>{setSelectedId(null);onProfile(selected.candidate.id,selected.job.id)}}>Abrir entrevista<ChevronRight size={15}/></Button></div></>}</DialogContent></Dialog></section>;
}
