import {interviewSummary,type InterviewGuide} from './interview-guide';
import type {Appointment} from './interview-agenda';
import type {InterviewInvitation} from './interview-invitation';
export type Criterion={id:string;text:string;kind:'experiencia'|'condicao'|'entrevista';priority:'obrigatorio'|'diferencial'|'confirmar'};
export type Candidate={id:string;name:string;role:string;city:string;source:string;text:string;phone:string;email:string;updated:string;demo:boolean;originalText?:string;editedAt?:string;verification?:Partial<Record<'phone'|'email'|'city',{at:string;method:string}>>;changeLog?:{at:string;fields:string[];confirmed:string[];method:string}[];fileKey?:string};
export type Evidence={criterionId:string;status:'encontrada'|'confirmar';quote:string;explanation:string;question:string};
export type Analysis={candidateId:string;evidence:Evidence[]};
export type RecordData={candidateId:string;jobId:string;status:string;interest:string;availability:string;notes:string;report:string;reportNeedsReview?:boolean;shortlisted?:boolean;invitation?:InterviewInvitation;interview?:InterviewGuide;appointments?:Appointment[];events:{at:string;text:string}[]};
export type Job={id:string;title:string;description:string;criteria:Criterion[];analyses:Analysis[];stage:number;engine:string;revision:number;updated:string};
export type Data={jobs:Job[];candidates:Candidate[];records:RecordData[];aiConfigured:boolean;version?:number};
export const sampleBrief='Procuro uma pessoa para atendimento em uma loja conceito na Avenida Paulista, São Paulo. Precisa de experiência com hospitalidade e varejo, além de disponibilidade para escala 6x1. Vai acolher clientes, vender e demonstrar produtos. É importante ter boa comunicação, curiosidade para aprender e colaboração com a equipe. Deve estar confortável atendendo públicos diversos.';
export const kindLabels={experiencia:'Experiência',condicao:'Condição da vaga',entrevista:'Avaliar em entrevista'};
export const priorityLabels={obrigatorio:'Obrigatório',diferencial:'Diferencial',confirmar:'A definir'};
export const demoCandidates:Candidate[]=[
{id:'demo-1',name:'Marina Costa',role:'Recepcionista de hotel',city:'São Paulo, SP',source:'Perfil fictício · exemplo',phone:'',email:'',updated:'',demo:true,text:'Recepcionista de hotel — 2022 a 2025. Experiência com hospitalidade: recepção de hóspedes, atendimento presencial, reservas e resolução de solicitações. Consultora de vendas em escola de idiomas — 2019 a 2021. Atendimento comercial e negociação de matrículas. Cidade declarada: São Paulo, SP. Objetivo: atendimento ao cliente. Disponibilidade para escala e demonstração de produtos não informadas.'},
{id:'demo-2',name:'Camila Oliveira',role:'Atendente de loja',city:'São Paulo, SP',source:'Perfil fictício · exemplo',phone:'',email:'',updated:'',demo:true,text:'Atendente de loja no varejo — 2021 a 2025. Atendimento ao público, fechamento de caixa, reposição e demonstração de produtos. Atuou com vendas de cosméticos e orientação sobre o uso de produtos. Cidade declarada: São Paulo, SP. Disponibilidade para escala não informada. Não há registro de experiência em hotelaria.'},
{id:'demo-3',name:'Rafael Santos',role:'Assistente de atendimento',city:'Osasco, SP',source:'Perfil fictício · exemplo',phone:'',email:'',updated:'',demo:true,text:'Assistente de atendimento em restaurante — 2020 a 2024. Acolhimento dos clientes, organização de reservas e apoio à equipe de salão. Curso de hospitalidade e atendimento ao cliente. Cidade declarada: Osasco, SP. Experiência em varejo e disponibilidade para escala não informadas.'},
{id:'demo-4',name:'Luiza Martins',role:'Assistente administrativo',city:'São Paulo, SP',source:'Perfil fictício · exemplo',phone:'',email:'',updated:'',demo:true,text:'Assistente administrativo — 2022 a 2025. Organização de documentos, planilhas, atualização de cadastros e atendimento telefônico. Cidade declarada: São Paulo, SP. Não informa atuação em loja ou recepção de hotel. Objetivo: área administrativa.'}
];
export const starterJob:Job={id:'example',title:'Atendimento · Loja conceito',description:sampleBrief,criteria:[],analyses:[],stage:0,engine:'Busca por termos',revision:1,updated:''};
export const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function draftCriteria(description:string):Criterion[]{return description.split(/\n|[.!?;]+/).map(s=>s.trim()).filter(Boolean).slice(0,20).map((text,i)=>({id:`criterion-${i}`,text,kind:/escala|localiza|sal[aá]rio|remunera|disponib|paulista|presencial|jornada/i.test(text)?'condicao':/curios|extrovert|colabora|comunica|divers/i.test(text)?'entrevista':'experiencia',priority:'confirmar'}));}
export function termAnalysis(candidates:Candidate[],criteria:Criterion[]):Analysis[]{
const stop=new Set(['experiencia','pessoa','precisa','procuro','importante','alem','para','como','deve','estar','atender','publicos','tenha','vaga','informada','informadas']);
return candidates.map(c=>({candidateId:c.id,evidence:criteria.map(k=>{const words=normalize(k.text).split(/[^a-z0-9]+/).filter(w=>w.length>3&&!stop.has(w));const sentences=c.text.split(/(?<=[.!?])\s+|\n/).filter(s=>!/(nao|não|sem)\s/i.test(s));const quote=k.kind==='experiencia'?sentences.find(s=>words.some(w=>normalize(s).includes(w)))||'':'';return {criterionId:k.id,status:quote?'encontrada':'confirmar',quote,explanation:quote?'Coincidência de termos. Revise o contexto: o trecho não comprova atendimento integral ao critério.':'Não há evidência validada para este critério.',question:`Pode contar uma experiência relacionada a: ${k.text}?`};})}));}
export function emptyRecord(candidateId:string,jobId:string):RecordData{return{candidateId,jobId,status:'Não contatado',interest:'Não confirmado',availability:'Não confirmada',notes:'',report:'',events:[]};}
export function reportDraft(c:Candidate,j:Job,r:RecordData):string{const a=j.analyses.find(a=>a.candidateId===c.id);const found=a?.evidence.filter(e=>e.status==='encontrada').map(e=>`${j.criteria.find(k=>k.id===e.criterionId)?.text}\nTrecho documental: “${e.quote}”`).join('\n\n')||'Sem evidências analisadas.';const pending=a?.evidence.filter(e=>e.status==='confirmar').map(e=>j.criteria.find(k=>k.id===e.criterionId)?.text).join('\n')||'Revise se há informações adicionais a confirmar.';return `PARECER PARA REVISÃO\n${c.name} — ${j.title}\n\nEXPERIÊNCIA DECLARADA\n${c.text}\n\nRELAÇÃO COM OS CRITÉRIOS\n${found}\n\nINFORMAÇÕES A CONFIRMAR\n${pending}\n\nREGISTROS DA RECRUTADORA\nInteresse: ${r.interest}\nDisponibilidade: ${r.availability}\n${r.notes||'Sem notas de entrevista.'}${interviewSummary(r.interview,j)?`\n\n${interviewSummary(r.interview,j)}`:''}\n\nPARECER DA RECRUTADORA\n[Inclua os motivos da sua recomendação e os pontos de atenção antes de compartilhar.]\n\nRequer revisão humana. Análise: ${j.engine}.`;}
