export type InterviewInvitation={recruiter:string;company:string;roleTitle:string;date:string;time:string;format:'a combinar'|'online'|'presencial';location:string;instructions:string;subject:string;emailBody:string;message:string;updated:string};
export function emptyInvitation(roleTitle:string):InterviewInvitation{return {recruiter:'',company:'',roleTitle,date:'',time:'',format:'a combinar',location:'',instructions:'',subject:'',emailBody:'',message:'',updated:''}}
export function validInterviewDate(value:string){if(!value)return true;if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(value+'T12:00:00Z');return !Number.isNaN(date.getTime())&&date.toISOString().slice(0,10)===value}
export function generateInvitation(candidateName:string,draft:InterviewInvitation):InterviewInvitation{
 if(!draft.recruiter.trim()||!draft.roleTitle.trim())throw Error('Informe seu nome e o nome da vaga para preparar os rascunhos.');
 if(!validInterviewDate(draft.date)||draft.time&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(draft.time))throw Error('Confira a data e o horário sugeridos.');
 const firstName=candidateName.trim().split(/\s+/)[0]||'tudo bem';
 const identity=`Sou ${draft.recruiter.trim()}${draft.company.trim()?`, responsável pelo recrutamento para ${draft.company.trim()}`:', recrutadora'}.`;
 const details=[draft.date?`Data sugerida: ${draft.date.split('-').reverse().join('/')}`:'',draft.time?`Horário sugerido: ${draft.time} (horário de Brasília)`:'',draft.format!=='a combinar'?`Formato: ${draft.format==='online'?'on-line':'presencial'}`:'',draft.location.trim()?`${draft.format==='online'?'Link ou instruções de acesso':draft.format==='presencial'?'Local':'Local ou link'}: ${draft.location.trim()}`:'',draft.instructions.trim()?`Orientações: ${draft.instructions.trim()}`:''].filter(Boolean).join('\n');
 const request=draft.date||draft.time?'Essa sugestão funciona para você? Se preferir outro dia ou horário, podemos combinar.':'Você tem interesse em conversar? Se sim, podemos combinar o melhor dia, horário e formato.';
 return {...draft,subject:`Convite para entrevista — ${draft.roleTitle.trim()}`,emailBody:`Olá, ${firstName}! Tudo bem?\n\n${identity}\n\nGostaria de convidar você para uma conversa sobre a oportunidade de ${draft.roleTitle.trim()}, para conhecer melhor sua trajetória e apresentar os detalhes da vaga.${details?`\n\n${details}`:''}\n\n${request}\n\nAguardo seu retorno.\n\nAtenciosamente,\n${draft.recruiter.trim()}${draft.company.trim()?`\n${draft.company.trim()}`:''}`,message:`Olá, ${firstName}! Tudo bem? ${identity} Gostaria de convidar você para uma conversa sobre a vaga de ${draft.roleTitle.trim()}.${details?`\n\n${details}`:''}\n\n${request}\n\nSe preferir não receber novos contatos, é só me avisar.`};
}
