import 'server-only';
import {configured,supabase} from './supabase/server';
import {starterJob,type Data,type Candidate} from './domain';
export class HttpError extends Error{constructor(message:string,public status=400){super(message)}}
export async function owner(){if(!configured())throw new HttpError('O acesso ainda está sendo configurado.',503);const {data:{user},error}=await (await supabase()).auth.getUser();if(error||!user)throw new HttpError('Entre na sua conta para acessar este espaço.',401);return user.id}
export async function database(){return supabase()}
export function aiConfigured(){return Boolean(process.env.ANTHROPIC_API_KEY)}
export function requestOrigin(request:Request){const url=new URL(request.url);const host=request.headers.get('host')||url.host;const protocol=request.headers.get('x-forwarded-proto')||url.protocol.replace(':','');if(protocol!=='https'&&protocol!=='http')throw new HttpError('Origem inválida.',403);return new URL(`${protocol}://${host}`).origin}
export function checkOrigin(request:Request){const origin=request.headers.get('origin');if(!origin||requestOrigin(request)!==origin)throw new HttpError('Origem da solicitação não autorizada.',403)}
export async function readData(id:string):Promise<Data>{const db=await database();const initial=await db.from('workspaces').select('jobs,records,version').eq('owner',id).maybeSingle();let row=initial.data;const error=initial.error;if(error)throw new HttpError('Não foi possível carregar o banco de dados.',503);if(!row){const first={...starterJob,id:crypto.randomUUID(),title:'Minha primeira vaga',description:'',criteria:[],analyses:[],stage:0};const result=await db.from('workspaces').upsert({owner:id,jobs:[first],records:[],version:1},{onConflict:'owner',ignoreDuplicates:true});if(result.error)throw new HttpError('Não foi possível criar seu espaço.',503);const result2=await db.from('workspaces').select('jobs,records,version').eq('owner',id).single();row=result2.data;if(result2.error||!row)throw new HttpError('Não foi possível carregar seu espaço.',503)}const candidates:Candidate[]=[];for(let offset=0;;offset+=500){const result=await db.from('candidates').select('payload').eq('owner',id).order('id').range(offset,offset+499);if(result.error)throw new HttpError('Não foi possível carregar os candidatos.',503);candidates.push(...result.data.map(r=>r.payload as Candidate));if(result.data.length<500)break}return{jobs:row.jobs,records:row.records,candidates,version:row.version,aiConfigured:aiConfigured()}}
export async function addCandidate(id:string,c:Candidate){const {error}=await (await database()).from('candidates').insert({owner:id,id:c.id,name:c.name,city:c.city,role:c.role,file_key:c.fileKey||null,payload:c});if(error)throw new HttpError('Não foi possível salvar o candidato. O currículo pode já estar cadastrado.',409)}
export function apiError(e:unknown){if(e instanceof HttpError)return Response.json({error:e.message},{status:e.status});if(e instanceof Error&&e.name==='ZodError')return Response.json({error:'Confira os campos: há informações inválidas ou muito longas.'},{status:400});console.error('Talentia request failed',e instanceof Error?e.name:'unknown');return Response.json({error:'Não foi possível concluir. Seus dados não foram descartados; tente novamente.'},{status:500})}
