import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {demoCandidates,starterJob,type Data,type Candidate} from './domain';
export class HttpError extends Error{constructor(message:string,public status=400){super(message)}}
export async function owner(){const u=await getChatGPTUser();if(!u)throw new HttpError('Entre na sua conta para acessar este espaço.',401);return u.userId}
export function database(){if(!env.DB)throw new HttpError('O banco de dados está temporariamente indisponível.',503);return env.DB}
export function aiConfigured(){return Boolean(env.ANTHROPIC_API_KEY)}
export function checkOrigin(request:Request){const origin=request.headers.get('origin');if(origin&&new URL(request.url).origin!==origin)throw new HttpError('Origem da solicitação não autorizada.',403)}
export async function readData(id:string):Promise<Data>{const db=database();let row=await db.prepare('SELECT jobs,records,version FROM workspaces WHERE owner=?').bind(id).first<{jobs:string;records:string;version:number}>();if(!row){const inserted=await db.prepare('INSERT OR IGNORE INTO workspaces (owner,jobs,records,version,updated) VALUES (?,?,?,1,?)').bind(id,JSON.stringify([starterJob]),'[]',new Date().toISOString()).run();if(inserted.meta.changes){await db.batch(demoCandidates.map(c=>db.prepare('INSERT OR IGNORE INTO candidates (owner,id,payload) VALUES (?,?,?)').bind(id,c.id,JSON.stringify(c))))}row=await db.prepare('SELECT jobs,records,version FROM workspaces WHERE owner=?').bind(id).first<{jobs:string;records:string;version:number}>()}if(!row)throw new HttpError('Não foi possível carregar seu espaço.',503);const result=await db.prepare('SELECT payload FROM candidates WHERE owner=? ORDER BY id').bind(id).all<{payload:string}>();return{jobs:JSON.parse(row.jobs),records:JSON.parse(row.records),candidates:result.results.map(r=>JSON.parse(r.payload)),version:row.version,aiConfigured:aiConfigured()}}
export async function addCandidate(id:string,c:Candidate){await database().prepare('INSERT INTO candidates (owner,id,payload) VALUES (?,?,?)').bind(id,c.id,JSON.stringify(c)).run()}
export function apiError(e:unknown){if(e instanceof HttpError)return Response.json({error:e.message},{status:e.status});if(e instanceof Error&&e.name==='ZodError')return Response.json({error:'Confira os campos: há informações inválidas ou muito longas.'},{status:400});console.error('Talentia request failed',e instanceof Error?e.name:'unknown');return Response.json({error:'Não foi possível concluir. Seus dados não foram descartados; tente novamente.'},{status:500})}
