import {z} from 'zod';
export const criterionSchema=z.object({id:z.string().min(1).max(100),text:z.string().min(1).max(2000),kind:z.enum(['experiencia','condicao','entrevista']),priority:z.enum(['obrigatorio','diferencial','confirmar'])});
export const evidenceSchema=z.object({criterionId:z.string().max(100),status:z.enum(['encontrada','confirmar']),quote:z.string().max(6000),explanation:z.string().max(2000),question:z.string().max(2000)});
export const analysisSchema=z.object({candidateId:z.string().max(100),evidence:z.array(evidenceSchema).max(30)});
export const jobSchema=z.object({id:z.string().min(1).max(100),title:z.string().min(1).max(200),description:z.string().max(20000),criteria:z.array(criterionSchema).max(30),analyses:z.array(analysisSchema).max(6000),stage:z.number().int().min(0).max(2),engine:z.string().max(100),revision:z.number().int(),updated:z.string().max(100)});
export const invitationSchema=z.object({recruiter:z.string().max(200),company:z.string().max(200),roleTitle:z.string().max(200),date:z.string().regex(/^(?:\d{4}-\d{2}-\d{2})?$/),time:z.string().regex(/^(?:([01]\d|2[0-3]):[0-5]\d)?$/),format:z.enum(['a combinar','online','presencial']),location:z.string().max(1000),instructions:z.string().max(2000),subject:z.string().max(500),emailBody:z.string().max(12000),message:z.string().max(6000),updated:z.string().max(100)});
export const recordSchema=z.object({candidateId:z.string().max(100),jobId:z.string().max(100),status:z.enum(['Não contatado','Contato realizado','Respondeu','Entrevista','Selecionado','Encerrado','Não contatar']),interest:z.enum(['Não confirmado','Interessado','Sem interesse']),availability:z.string().max(2000),notes:z.string().max(20000),report:z.string().max(80000),invitation:invitationSchema.optional(),events:z.array(z.object({at:z.string().max(100),text:z.string().max(500)})).max(500)});
export const candidateSchema=z.object({id:z.string().min(1).max(100),name:z.string().min(1).max(200),role:z.string().max(300),city:z.string().max(300),source:z.string().max(300),text:z.string().min(30).max(80000),phone:z.string().max(100),email:z.string().max(300),updated:z.string().max(100),demo:z.boolean(),fileKey:z.string().max(500).optional()});
export function assertFairCriteria(criteria:{text:string}[]){const forbidden=/\b(idade|sexo|estado civil|religião|religiao|raça|raca|etnia|gênero|genero|orientação sexual|orientacao sexual|aparência|aparencia|sem filhos|com filhos)\b/i;if(criteria.some(c=>forbidden.test(c.text)))throw new Error('Revise os critérios: use experiências, competências e condições de trabalho, sem atributos pessoais protegidos.');}
export function professionalText(text:string){return text.split('\n').filter(line=>!/^\s*(idade|sexo|estado civil|data de nascimento|nascimento|endere[cç]o|cep|telefone|e-?mail)\s*:/i.test(line)).join('\n');}
