'use client';
import {useState,type FormEvent} from 'react';
import {HeartHandshake} from 'lucide-react';
import {useRouter} from 'next/navigation';
import {browserClient} from '@/lib/supabase/browser';
import {Button} from '@/components/ui/button';
export default function AuthForm({configured,reset=false}:{configured:boolean;reset?:boolean}){
const router=useRouter();
const [mode,setMode]=useState(reset?'reset':'login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
async function submit(e:FormEvent){e.preventDefault();if(!configured)return;setBusy(true);setMessage('');try{const client=browserClient();if(mode==='login'){const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;router.replace('/');router.refresh()}else if(mode==='signup'){const {error}=await client.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/auth/callback`}});if(error)throw error;setMessage('Confira seu e-mail para confirmar a conta.')}else if(mode==='forgot'){const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/auth/callback?next=/reset-password`});if(error)throw error;setMessage('Se houver uma conta para este e-mail, você receberá as instruções.')}else{const {data:{user},error:authError}=await client.auth.getUser();if(authError||!user)throw Error('Link inválido');const {error}=await client.auth.updateUser({password});if(error)throw error;await client.auth.signOut();router.replace('/login');router.refresh()}}catch{setMessage(mode==='login'?'Não foi possível entrar. Confira o e-mail, a senha e a confirmação da conta.':'Não foi possível concluir. Confira os dados ou solicite um novo link.')}finally{setBusy(false)}}
return <main className="auth-shell"><section className="auth-story" aria-label="Sobre a Talentia"><span className="eyebrow">FEITO PARA O SEU OLHAR</span><h2>Conecte histórias.<br/><em>Encontre talentos.</em></h2><p>Um espaço para conhecer cada trajetória, organizar suas oportunidades e dedicar mais tempo às pessoas.</p><div className="auth-story-note"><HeartHandshake size={23}/><span>A tecnologia apoia. A sensibilidade é sua.</span></div></section><section className="auth-card"><div className="brand">talentia<span>.</span></div><h1>{mode==='login'?'Bem-vinda ao seu espaço.':mode==='signup'?'Crie sua conta.':mode==='forgot'?'Recupere seu acesso.':'Escolha uma nova senha.'}</h1><p>Organize suas vagas, encontre evidências e reúna seus pareceres.</p>{!configured?<p role="status">O acesso está sendo preparado. Falta conectar o banco de dados para liberar os logins.</p>:<><form onSubmit={submit}>{mode!=='reset'&&<label>E-mail<input className="text-input" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}{mode!=='forgot'&&<label>Senha<input className="text-input" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?1:12} required value={password} onChange={e=>setPassword(e.target.value)}/>{mode!=='login'&&<small>Use pelo menos 12 caracteres.</small>}</label>}<Button className="primary-button" disabled={busy}>{busy?'Aguarde…':mode==='login'?'Entrar':mode==='signup'?'Criar conta':mode==='forgot'?'Enviar instruções':'Salvar nova senha'}</Button></form><p role="status" aria-live="polite">{message}</p>{!reset&&<div className="auth-links"><button onClick={()=>{setMode(mode==='signup'?'login':'signup');setMessage('')}}>{mode==='signup'?'Já tenho uma conta':'Criar conta'}</button><button onClick={()=>{setMode(mode==='forgot'?'login':'forgot');setMessage('')}}>{mode==='forgot'?'Voltar ao login':'Esqueci minha senha'}</button></div>}</>}<small>Os currículos e pareceres ficam no espaço da sua conta.</small></section></main>
}
